#!/usr/bin/env python3
"""
Generates src/lang/<code>.json for every supported language from the
translation table below. Run manually whenever UI strings change; this is a
build-time helper, not something the app runs in the browser.
"""
import json
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "lang")

MODEL_IDS = [
    "gemini-3.1-pro-preview",
    "gemini-3.7-flash",
    "gemini-3.6-flash",
    "gemini-3.5-flash",
    "gemini-2.5-pro",
    "gemini-2.5-flash-lite",
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "claude-sonnet-5",
    "claude-haiku-4-5-20251001",
]

# (emoji, paid/free-ish qualifier per language handled inline below)
MODEL_EMOJI = ["✨", "⚡", "⚡", "🔵", "🟢", "⚪", "🐋", "🐋", "🟠", "🟡"]

# name shown for each model, per language (kept short & consistent)
MODEL_NAMES = {
    "fa": ["جمینای ۳.۱ پرو (پیش‌نمایش - پیشرفته/پولی)", "جمینای ۳.۷ فلش (جدیدترین)", "جمینای ۳.۶ فلش",
           "جمینای ۳.۵ فلش", "جمینای ۲.۵ پرو (پولی)", "جمینای ۲.۵ فلش-لایت (سریع و کم‌هزینه*)"],
    "en": ["Gemini 3.1 Pro (Preview - Advanced/Paid)", "Gemini 3.7 Flash (Newest)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (Paid)", "Gemini 2.5 Flash-Lite (Fast & cheap*)", "DeepSeek V4 Flash (Fast & cheap*)", "DeepSeek V4 Pro (Advanced/Paid)", "Claude Sonnet 5 (Balanced/Paid)", "Claude Haiku 4.5 (Fast & cheap*)"],
    "ar": ["Gemini 3.1 Pro (معاينة - متقدم/مدفوع)", "Gemini 3.7 Flash (الأحدث)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (مدفوع)", "Gemini 2.5 Flash-Lite (سريع وغير مكلف*)", "DeepSeek V4 Flash (سريع وغير مكلف*)", "DeepSeek V4 Pro (متقدم/مدفوع)", "Claude Sonnet 5 (متوازن/مدفوع)", "Claude Haiku 4.5 (سريع وغير مكلف*)"],
    "tr": ["Gemini 3.1 Pro (Önizleme - Gelişmiş/Ücretli)", "Gemini 3.7 Flash (En yeni)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (Ücretli)", "Gemini 2.5 Flash-Lite (Hızlı ve ucuz*)", "DeepSeek V4 Flash (Hızlı ve ucuz*)", "DeepSeek V4 Pro (Gelişmiş/Ücretli)", "Claude Sonnet 5 (Dengeli/Ücretli)", "Claude Haiku 4.5 (Hızlı ve ucuz*)"],
    "fr": ["Gemini 3.1 Pro (Aperçu - Avancé/Payant)", "Gemini 3.7 Flash (Le plus récent)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (Payant)", "Gemini 2.5 Flash-Lite (Rapide et économique*)", "DeepSeek V4 Flash (Rapide et économique*)", "DeepSeek V4 Pro (Avancé/Payant)", "Claude Sonnet 5 (Équilibré/Payant)", "Claude Haiku 4.5 (Rapide et économique*)"],
    "de": ["Gemini 3.1 Pro (Vorschau - Erweitert/Kostenpflichtig)", "Gemini 3.7 Flash (Neueste)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (Kostenpflichtig)", "Gemini 2.5 Flash-Lite (Schnell & günstig*)", "DeepSeek V4 Flash (Schnell & günstig*)", "DeepSeek V4 Pro (Erweitert/Kostenpflichtig)", "Claude Sonnet 5 (Ausgewogen/Kostenpflichtig)", "Claude Haiku 4.5 (Schnell & günstig*)"],
    "es": ["Gemini 3.1 Pro (Vista previa - Avanzado/De pago)", "Gemini 3.7 Flash (Más reciente)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (De pago)", "Gemini 2.5 Flash-Lite (Rápido y económico*)", "DeepSeek V4 Flash (Rápido y económico*)", "DeepSeek V4 Pro (Avanzado/De pago)", "Claude Sonnet 5 (Equilibrado/De pago)", "Claude Haiku 4.5 (Rápido y económico*)"],
    "ru": ["Gemini 3.1 Pro (Превью - Продвинутая/Платная)", "Gemini 3.7 Flash (Новейшая)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (Платная)", "Gemini 2.5 Flash-Lite (Быстрая и недорогая*)", "DeepSeek V4 Flash (Быстрая и недорогая*)", "DeepSeek V4 Pro (Продвинутая/Платная)", "Claude Sonnet 5 (Сбалансированная/Платная)", "Claude Haiku 4.5 (Быстрая и недорогая*)"],
    "zh": ["Gemini 3.1 Pro（预览版 - 高级/付费）", "Gemini 3.7 Flash（最新）", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro（付费）", "Gemini 2.5 Flash-Lite（快速且经济*）", "DeepSeek V4 Flash（快速且经济*）", "DeepSeek V4 Pro（高级/付费）", "Claude Sonnet 5（均衡/付费）", "Claude Haiku 4.5（快速且经济*）"],
    "hi": ["Gemini 3.1 Pro (प्रीव्यू - एडवांस्ड/पेड)", "Gemini 3.7 Flash (नवीनतम)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (पेड)", "Gemini 2.5 Flash-Lite (तेज़ और सस्ता*)", "DeepSeek V4 Flash (तेज़ और सस्ता*)", "DeepSeek V4 Pro (एडवांस्ड/पेड)", "Claude Sonnet 5 (संतुलित/पेड)", "Claude Haiku 4.5 (तेज़ और सस्ता*)"],
    "ja": ["Gemini 3.1 Pro（プレビュー・上級/有料）", "Gemini 3.7 Flash（最新）", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro（有料）", "Gemini 2.5 Flash-Lite（高速・低コスト*）", "DeepSeek V4 Flash（高速・低コスト*）", "DeepSeek V4 Pro（上級/有料）", "Claude Sonnet 5（バランス型/有料）", "Claude Haiku 4.5（高速・低コスト*）"],
    "pt": ["Gemini 3.1 Pro (Prévia - Avançado/Pago)", "Gemini 3.7 Flash (Mais recente)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (Pago)", "Gemini 2.5 Flash-Lite (Rápido e econômico*)", "DeepSeek V4 Flash (Rápido e econômico*)", "DeepSeek V4 Pro (Avançado/Pago)", "Claude Sonnet 5 (Equilibrado/Pago)", "Claude Haiku 4.5 (Rápido e econômico*)"],
    "it": ["Gemini 3.1 Pro (Anteprima - Avanzato/A pagamento)", "Gemini 3.7 Flash (Più recente)", "Gemini 3.6 Flash",
           "Gemini 3.5 Flash", "Gemini 2.5 Pro (A pagamento)", "Gemini 2.5 Flash-Lite (Veloce ed economico*)", "DeepSeek V4 Flash (Veloce ed economico*)", "DeepSeek V4 Pro (Avanzato/A pagamento)", "Claude Sonnet 5 (Equilibrato/A pagamento)", "Claude Haiku 4.5 (Veloce ed economico*)"],
}

TONES = {
    "fa": ["رسمی", "معیار", "محاوره‌ای", "کوچه‌بازاری", "ادبی", "فاخر", "تخصصی", "ساده", "کودکانه"],
    "en": ["Formal", "Standard", "Colloquial", "Slang", "Literary", "Elegant", "Technical", "Simple", "Childlike"],
    "ar": ["رسمي", "قياسي", "عامي", "دارج", "أدبي", "فاخر", "تقني", "بسيط", "للأطفال"],
    "tr": ["Resmi", "Standart", "Konuşma dili", "Argo", "Edebi", "Zarif", "Teknik", "Basit", "Çocuksu"],
    "fr": ["Formel", "Standard", "Familier", "Argotique", "Littéraire", "Élégant", "Technique", "Simple", "Enfantin"],
    "de": ["Formell", "Standard", "Umgangssprachlich", "Slang", "Literarisch", "Elegant", "Technisch", "Einfach", "Kindlich"],
    "es": ["Formal", "Estándar", "Coloquial", "Jerga", "Literario", "Elegante", "Técnico", "Simple", "Infantil"],
    "ru": ["Формальный", "Стандартный", "Разговорный", "Сленговый", "Литературный", "Изысканный", "Технический", "Простой", "Детский"],
    "zh": ["正式", "标准", "口语化", "俚语", "文学性", "优雅", "技术性", "简单", "童趣"],
    "hi": ["औपचारिक", "मानक", "बोलचाल", "स्लैंग", "साहित्यिक", "सुरुचिपूर्ण", "तकनीकी", "सरल", "बचकाना"],
    "ja": ["フォーマル", "標準", "口語", "スラング", "文学的", "上品", "専門的", "シンプル", "子供向け"],
    "pt": ["Formal", "Padrão", "Coloquial", "Gíria", "Literário", "Elegante", "Técnico", "Simples", "Infantil"],
    "it": ["Formale", "Standard", "Colloquiale", "Gergale", "Letterario", "Elegante", "Tecnico", "Semplice", "Infantile"],
}

# Core UI strings per language. Keys must match across all languages.
STRINGS = {
"en": {
    "appTitle": "SubMovies - AI Subtitle Translator",
    "appHeaderTitle": "SubMovies AI Translator",
    "appSubtitle": "Translate your subtitles hassle-free, with precision.",
    "apiKeyLabel": "API Key:",
    "apiKeyPlaceholder": "Enter your API key here",
    "saveApiKeyLabel": "Save API Key",
    "modelLabel": "AI Model:",
    "temperatureLabel": "Creativity Level:",
    "toneLabel": "Translation Tone:",
    "langTargetLabel": "Target Language:",
    "filenameLabel": "Output File Name:",
    "filenamePlaceholder": "e.g. MyTranslatedMovie.srt",
    "translateBtn": "Translate Subtitles",
    "fileChooseLabel": "Upload .srt, .vtt, .ass, or .ssa file:",
    "fileChooseButtonText": "Choose File",
    "fileNone": "No file chosen",
    "charCountLabel": "Characters: {count}",
    "promptPlaceholder": "Or paste subtitle text here (SRT, VTT, or ASS format is auto-detected)",
    "downloadBtn": "Download Translated File",
    "copyBtnText": "Copy",
    "copySuccess": "Copied to clipboard!",
    "copyFail": "Failed to copy text.",
    "translatingPlaceholder": "Translating... please wait.",
    "responseTitle": "Translation Comparison",
    "originalTitle": "Original Text",
    "translatedTitle": "Translated Text",
    "themeToggleLight": "Switch to Light Mode",
    "themeToggleDark": "Switch to Dark Mode",
    "closeBtnLabel": "Close",
    "footerMadeWith": "Made with",
    "footerBy": "by",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "Invalid SRT file. Please check the format.",
    "fileValidationVTTError": "Invalid VTT file. Missing WEBVTT header or malformed.",
    "fileValidationASSError": "Invalid ASS/SSA file. Could not find [Script Info], [Events], or Dialogue lines.",
    "unsupportedFileType": "Unsupported file type. Please upload a .srt, .vtt, .ass, or .ssa file.",
    "fileReadError": "Error reading the file. It may be corrupted or too large.",
    "charCountWarning": "Warning: Very long text may take longer or hit API limits.",
    "errorMissing": "API key and subtitle text are required.",
    "errorAPI": "API Error: {message}",
    "errorNetwork": "Network error. Please check your internet connection.",
    "errorUnknown": "An unknown error occurred. Please try again.",
    "errorNoDownloadText": "No translated text available to download.",
    "apiKeyTooltip": "Enter the API key for your selected provider: from Google AI Studio for Gemini models, from the DeepSeek platform for DeepSeek models, or from the Anthropic console for Claude models. The key is only used for, and stored under, that provider.",
    "saveApiKeyTooltip": "If checked, your API key is stored locally in your browser. Uncheck to remove it.",
    "modelTooltip": "AI models are updated and retired frequently. Models marked with * are usually faster/cheaper but have tighter usage limits. Always check exact model IDs and current pricing on the official docs: ai.google.dev/gemini-api/docs/models for Gemini, api-docs.deepseek.com for DeepSeek, docs.claude.com for Claude.",
    "temperatureTooltip": "Lower values (e.g. 0.2) give more predictable, literal translations. Higher values (e.g. 0.9) encourage more creativity and word variety. Default: 0.7",
    "toneTooltip": "Choose the style and tone for the translated dialogue to match your content's context.",
    "targetLangTooltip": "Choose the language you want the subtitles translated into.",
    "uploadFileTooltip": "Click to upload a subtitle file (.srt, .vtt, .ass, or .ssa) from your device.",
    "outputFileNameTooltip": "Enter a custom name for the translated file. If left empty, a name will be generated automatically.",
    "customPromptLabel": "Custom Instructions (optional):",
    "customPromptPlaceholder": "e.g. Don't translate character names / use a humorous tone / use casual, everyday wording...",
    "customPromptTooltip": "Add any extra instructions you want the model to follow while translating. This is applied as extra style/context guidance and can't override the SRT/VTT formatting rules.",
    "stopBtn": "Stop Translation",
    "translatingProgress": "Translating chunk {current} of {total}...",
    "translationCancelled": "Translation was cancelled by the user.",
    "manualModeLabel": "Manual Translation Mode (no AI)",
    "manualModeTooltip": "Turn this on to translate line-by-line yourself instead of using AI. The original text appears on the left; type your translation on the right. Everything is saved automatically.",
    "manualEditorTitle": "Manual Translation Editor",
    "manualEditorEmptyHint": "Upload a subtitle file or paste its text above to get started.",
    "manualTranslationPlaceholder": "Type your translation here...",
    "manualDownloadBtn": "Download Translated SRT File",
    "manualAutoSaveHint": "Everything is saved automatically in this browser.",
    "chunkSizeLabel": "Processing Size Per Step:",
    "chunkSizeTooltip": "How many subtitle lines are sent to the model per request. A smaller size is more stable but needs more requests; a larger size is faster and cheaper but slightly raises the risk of lines getting out of sync.",
    "chunkSizeOptimal": "Optimal (Recommended)",
    "chunkSizeHigh": "High",
    "chunkSizeVeryHigh": "Very High",
    "resumeBtn": "Resume Translation",
    "partialTranslationSaved": "{current} of {total} parts translated. Click \"Resume Translation\" to continue from here.",
    "rateLimitLabel": "Delay Between Requests:",
    "rateLimitTooltip": "Adds a pause between consecutive requests to the model, lowering the chance of hitting the provider's rate limit. Useful for large files or free-tier accounts.",
    "rateLimitOff": "Off",
    "rateLimitLow": "Low (1s)",
    "rateLimitMedium": "Medium (3s)",
    "rateLimitHigh": "High (6s)",
    "postProcessLabel": "Auto-fix Long Lines",
    "postProcessTooltip": "After translating, automatically splits lines that got too long into two, for better subtitle readability. Only applies to SRT/VTT.",
    "assFormatNote": "For ASS/SSA files, only the dialogue text is translated - styling, timing, and effects are left untouched.",
},
"ar": {
    "appTitle": "SubMovies - مترجم الترجمات الذكي",
    "appHeaderTitle": "مترجم SubMovies الذكي",
    "appSubtitle": "ترجم ترجماتك بسهولة ودقة.",
    "apiKeyLabel": "مفتاح API:",
    "apiKeyPlaceholder": "أدخل مفتاح API هنا",
    "saveApiKeyLabel": "حفظ مفتاح API",
    "modelLabel": "نموذج الذكاء الاصطناعي:",
    "temperatureLabel": "مستوى الإبداع:",
    "toneLabel": "أسلوب الترجمة:",
    "langTargetLabel": "اللغة الهدف:",
    "filenameLabel": "اسم ملف الإخراج:",
    "filenamePlaceholder": "مثال: MyTranslatedMovie.srt",
    "translateBtn": "ترجمة الترجمات",
    "fileChooseLabel": "رفع ملف .srt أو .vtt أو .ass أو .ssa:",
    "fileChooseButtonText": "اختر ملفًا",
    "fileNone": "لم يتم اختيار ملف",
    "charCountLabel": "عدد الأحرف: {count}",
    "promptPlaceholder": "أو الصق نص الترجمة هنا (يتم التعرف تلقائيًا على تنسيق SRT أو VTT أو ASS)",
    "downloadBtn": "تنزيل الملف المترجم",
    "copyBtnText": "نسخ",
    "copySuccess": "تم النسخ إلى الحافظة!",
    "copyFail": "فشل نسخ النص.",
    "translatingPlaceholder": "جارٍ الترجمة... يرجى الانتظار.",
    "responseTitle": "مقارنة الترجمة",
    "originalTitle": "النص الأصلي",
    "translatedTitle": "النص المترجم",
    "themeToggleLight": "التبديل إلى الوضع الفاتح",
    "themeToggleDark": "التبديل إلى الوضع الداكن",
    "closeBtnLabel": "إغلاق",
    "footerMadeWith": "صُنع بـ",
    "footerBy": "بواسطة",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "ملف SRT غير صالح. يرجى التحقق من التنسيق.",
    "fileValidationVTTError": "ملف VTT غير صالح. رأس WEBVTT مفقود أو التنسيق غير صحيح.",
    "fileValidationASSError": "ملف ASS/SSA غير صالح. تعذر العثور على [Script Info] أو [Events] أو أسطر Dialogue.",
    "unsupportedFileType": "نوع الملف غير مدعوم. يرجى رفع ملف .srt أو .vtt أو .ass أو .ssa.",
    "fileReadError": "خطأ في قراءة الملف. قد يكون تالفًا أو كبيرًا جدًا.",
    "charCountWarning": "تحذير: النص الطويل جدًا قد يستغرق وقتًا أطول أو يواجه حدود API.",
    "errorMissing": "مفتاح API ونص الترجمة مطلوبان.",
    "errorAPI": "خطأ في API: {message}",
    "errorNetwork": "خطأ في الشبكة. يرجى التحقق من اتصال الإنترنت.",
    "errorUnknown": "حدث خطأ غير معروف. يرجى المحاولة مرة أخرى.",
    "errorNoDownloadText": "لا يوجد نص مترجم متاح للتنزيل.",
    "apiKeyTooltip": "أدخل مفتاح API الخاص بمزوّد الخدمة المحدد: من Google AI Studio لنماذج Gemini، من منصة DeepSeek لنماذج DeepSeek، أو من وحدة تحكم Anthropic لنماذج Claude. يُستخدم المفتاح ويُخزَّن لهذا المزوّد فقط.",
    "saveApiKeyTooltip": "إذا تم التحديد، سيتم تخزين مفتاح API محليًا في متصفحك. ألغِ التحديد لإزالته.",
    "modelTooltip": "يتم تحديث نماذج الذكاء الاصطناعي وإيقافها بشكل متكرر. النماذج المعلّمة بـ * عادةً أسرع/أرخص لكن لها حدود استخدام أكثر صرامة. تحقق دائمًا من المعرفات الدقيقة والأسعار من المستندات الرسمية: ai.google.dev/gemini-api/docs/models لـ Gemini، و api-docs.deepseek.com لـ DeepSeek، و docs.claude.com لـ Claude.",
    "temperatureTooltip": "القيم المنخفضة (مثل 0.2) تعطي ترجمة أكثر دقة وقابلية للتنبؤ. القيم الأعلى (مثل 0.9) تشجع على الإبداع وتنوع الكلمات. الافتراضي: 0.7",
    "toneTooltip": "اختر الأسلوب والنبرة المناسبين للحوار المترجم ليتوافقا مع سياق المحتوى.",
    "targetLangTooltip": "اختر اللغة التي تريد ترجمة الترجمات إليها.",
    "uploadFileTooltip": "انقر لرفع ملف ترجمة (.srt أو .vtt أو .ass أو .ssa) من جهازك.",
    "outputFileNameTooltip": "أدخل اسمًا مخصصًا للملف المترجم. إذا تُرك فارغًا، سيتم إنشاء اسم تلقائيًا.",
    "customPromptLabel": "تعليمات مخصصة (اختياري):",
    "customPromptPlaceholder": "مثال: لا تترجم أسماء الشخصيات / استخدم أسلوبًا فكاهيًا / استخدم لهجة عامية بسيطة...",
    "customPromptTooltip": "أضف أي تعليمات إضافية تريد أن يتبعها النموذج أثناء الترجمة. تُطبَّق كإرشادات أسلوب/سياق إضافية ولا يمكنها تجاوز قواعد تنسيق SRT/VTT.",
    "stopBtn": "إيقاف الترجمة",
    "translatingProgress": "جارٍ ترجمة الجزء {current} من {total}...",
    "translationCancelled": "تم إلغاء الترجمة من قبل المستخدم.",
    "manualModeLabel": "وضع الترجمة اليدوية (بدون ذكاء اصطناعي)",
    "manualModeTooltip": "فعّل هذا الوضع لترجمة كل سطر بنفسك بدلاً من استخدام الذكاء الاصطناعي. يظهر النص الأصلي على اليسار، واكتب ترجمتك على اليمين. يتم حفظ كل شيء تلقائيًا.",
    "manualEditorTitle": "محرر الترجمة اليدوية",
    "manualEditorEmptyHint": "قم برفع ملف ترجمة أو الصق نصه أعلاه للبدء.",
    "manualTranslationPlaceholder": "اكتب ترجمتك هنا...",
    "manualDownloadBtn": "تنزيل ملف SRT المترجم",
    "manualAutoSaveHint": "يتم حفظ كل شيء تلقائيًا في هذا المتصفح.",
    "chunkSizeLabel": "حجم المعالجة في كل مرحلة:",
    "chunkSizeTooltip": "عدد أسطر الترجمة المرسلة إلى النموذج في كل طلب. القيمة الأصغر أكثر استقرارًا لكنها تحتاج طلبات أكثر؛ القيمة الأكبر أسرع وأرخص لكنها تزيد قليلاً من خطر اختلال ترتيب الأسطر.",
    "chunkSizeOptimal": "مثالي (موصى به)",
    "chunkSizeHigh": "مرتفع",
    "chunkSizeVeryHigh": "مرتفع جدًا",
    "resumeBtn": "متابعة الترجمة",
    "partialTranslationSaved": "تمت ترجمة {current} من {total} جزء. اضغط على \"متابعة الترجمة\" للاستكمال من هنا.",
    "rateLimitLabel": "التأخير بين الطلبات:",
    "rateLimitTooltip": "يضيف توقفًا بين الطلبات المتتالية إلى النموذج، مما يقلل احتمالية الوصول إلى حد معدل الاستخدام لدى مزوّد الخدمة. مفيد للملفات الكبيرة أو الحسابات المجانية.",
    "rateLimitOff": "إيقاف",
    "rateLimitLow": "منخفض (١ ثانية)",
    "rateLimitMedium": "متوسط (٣ ثوانٍ)",
    "rateLimitHigh": "مرتفع (٦ ثوانٍ)",
    "postProcessLabel": "إصلاح الأسطر الطويلة تلقائيًا",
    "postProcessTooltip": "بعد الترجمة، يقسّم تلقائيًا الأسطر التي أصبحت طويلة جدًا إلى سطرين لتحسين قابلية قراءة الترجمة. يُطبَّق فقط على SRT/VTT.",
    "assFormatNote": "بالنسبة لملفات ASS/SSA، يُترجم نص الحوار فقط - يبقى التنسيق والتوقيت والتأثيرات دون تغيير.",
},
"tr": {
    "appTitle": "SubMovies - Yapay Zeka Altyazı Çevirmeni",
    "appHeaderTitle": "SubMovies Akıllı Çevirmen",
    "appSubtitle": "Altyazılarınızı sorunsuz ve hassas şekilde çevirin.",
    "apiKeyLabel": "API Anahtarı:",
    "apiKeyPlaceholder": "API anahtarınızı buraya girin",
    "saveApiKeyLabel": "API Anahtarını Kaydet",
    "modelLabel": "Yapay Zeka Modeli:",
    "temperatureLabel": "Yaratıcılık Düzeyi:",
    "toneLabel": "Çeviri Tonu:",
    "langTargetLabel": "Hedef Dil:",
    "filenameLabel": "Çıktı Dosya Adı:",
    "filenamePlaceholder": "örn: MyTranslatedMovie.srt",
    "translateBtn": "Altyazıları Çevir",
    "fileChooseLabel": ".srt, .vtt, .ass veya .ssa dosyası yükleyin:",
    "fileChooseButtonText": "Dosya Seç",
    "fileNone": "Dosya seçilmedi",
    "charCountLabel": "Karakter sayısı: {count}",
    "promptPlaceholder": "Ya da altyazı metnini buraya yapıştırın (SRT, VTT veya ASS formatı otomatik algılanır)",
    "downloadBtn": "Çevrilmiş Dosyayı İndir",
    "copyBtnText": "Kopyala",
    "copySuccess": "Panoya kopyalandı!",
    "copyFail": "Metin kopyalanamadı.",
    "translatingPlaceholder": "Çevriliyor... lütfen bekleyin.",
    "responseTitle": "Çeviri Karşılaştırması",
    "originalTitle": "Orijinal Metin",
    "translatedTitle": "Çevrilmiş Metin",
    "themeToggleLight": "Açık moda geç",
    "themeToggleDark": "Koyu moda geç",
    "closeBtnLabel": "Kapat",
    "footerMadeWith": "ile yapıldı",
    "footerBy": "yapan:",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "Geçersiz SRT dosyası. Lütfen formatı kontrol edin.",
    "fileValidationVTTError": "Geçersiz VTT dosyası. WEBVTT başlığı eksik veya format hatalı.",
    "fileValidationASSError": "Geçersiz ASS/SSA dosyası. [Script Info], [Events] veya Dialogue satırları bulunamadı.",
    "unsupportedFileType": "Desteklenmeyen dosya türü. Lütfen .srt, .vtt, .ass veya .ssa dosyası yükleyin.",
    "fileReadError": "Dosya okunurken hata oluştu. Bozuk veya çok büyük olabilir.",
    "charCountWarning": "Uyarı: Çok uzun metin daha uzun sürebilir veya API sınırlarına takılabilir.",
    "errorMissing": "API anahtarı ve altyazı metni gereklidir.",
    "errorAPI": "API Hatası: {message}",
    "errorNetwork": "Ağ hatası. Lütfen internet bağlantınızı kontrol edin.",
    "errorUnknown": "Bilinmeyen bir hata oluştu. Lütfen tekrar deneyin.",
    "errorNoDownloadText": "İndirilecek çevrilmiş metin yok.",
    "apiKeyTooltip": "Seçtiğiniz sağlayıcının API anahtarını girin: Gemini modelleri için Google AI Studio'dan, DeepSeek modelleri için DeepSeek platformundan, Claude modelleri için Anthropic konsolundan. Bu anahtar yalnızca o sağlayıcı için kullanılır ve saklanır.",
    "saveApiKeyTooltip": "İşaretlenirse API anahtarınız tarayıcınızda yerel olarak saklanır. Kaldırmak için işareti kaldırın.",
    "modelTooltip": "Yapay zeka modelleri sık sık güncellenir ve kullanımdan kaldırılır. * işaretli modeller genellikle daha hızlı/ucuzdur ancak kullanım limitleri daha sıkıdır. Kesin model kimliklerini ve güncel fiyatlandırmayı resmi belgelerden kontrol edin: Gemini için ai.google.dev/gemini-api/docs/models, DeepSeek için api-docs.deepseek.com, Claude için docs.claude.com.",
    "temperatureTooltip": "Düşük değerler (örn. 0.2) daha öngörülebilir, birebir çeviriler verir. Yüksek değerler (örn. 0.9) daha fazla yaratıcılık ve kelime çeşitliliğini teşvik eder. Varsayılan: 0.7",
    "toneTooltip": "İçeriğinizin bağlamına uyacak şekilde çevrilen diyalog için stil ve tonu seçin.",
    "targetLangTooltip": "Altyazıların çevrilmesini istediğiniz dili seçin.",
    "uploadFileTooltip": "Cihazınızdan bir altyazı dosyası (.srt, .vtt, .ass veya .ssa) yüklemek için tıklayın.",
    "outputFileNameTooltip": "Çevrilmiş dosya için özel bir ad girin. Boş bırakılırsa otomatik olarak bir ad oluşturulur.",
    "customPromptLabel": "Özel Talimatlar (isteğe bağlı):",
    "customPromptPlaceholder": "örn: Karakter isimlerini çevirme / esprili bir ton kullan / günlük konuşma dili kullan...",
    "customPromptTooltip": "Modelin çeviri sırasında uyması için ek talimatlar ekleyin. Bu, ekstra stil/bağlam rehberi olarak uygulanır ve SRT/VTT biçimlendirme kurallarını geçersiz kılamaz.",
    "stopBtn": "Çeviriyi Durdur",
    "translatingProgress": "{total} parçadan {current}. parça çevriliyor...",
    "translationCancelled": "Çeviri kullanıcı tarafından iptal edildi.",
    "manualModeLabel": "Manuel Çeviri Modu (yapay zeka olmadan)",
    "manualModeTooltip": "Yapay zeka yerine satır satır kendiniz çevirmek için bunu açın. Orijinal metin solda görünür; çevirinizi sağa yazın. Her şey otomatik olarak kaydedilir.",
    "manualEditorTitle": "Manuel Çeviri Düzenleyicisi",
    "manualEditorEmptyHint": "Başlamak için bir altyazı dosyası yükleyin veya metnini yukarıya yapıştırın.",
    "manualTranslationPlaceholder": "Çevirinizi buraya yazın...",
    "manualDownloadBtn": "Çevrilmiş SRT Dosyasını İndir",
    "manualAutoSaveHint": "Her şey bu tarayıcıda otomatik olarak kaydedilir.",
    "chunkSizeLabel": "Adım Başına İşlem Hacmi:",
    "chunkSizeTooltip": "Her istekte modele kaç altyazı satırı gönderileceği. Küçük değer daha kararlıdır ama daha fazla istek gerektirir; büyük değer daha hızlı ve ucuzdur ama satırların senkronizasyonunun bozulma riskini biraz artırır.",
    "chunkSizeOptimal": "Optimum (Önerilen)",
    "chunkSizeHigh": "Yüksek",
    "chunkSizeVeryHigh": "Çok Yüksek",
    "resumeBtn": "Çeviriye Devam Et",
    "partialTranslationSaved": "{total} parçadan {current} tanesi çevrildi. Buradan devam etmek için \"Çeviriye Devam Et\"e tıklayın.",
    "rateLimitLabel": "İstekler Arası Gecikme:",
    "rateLimitTooltip": "Modele yapılan ardışık istekler arasına bir duraklama ekler, sağlayıcının hız sınırına takılma olasılığını azaltır. Büyük dosyalar veya ücretsiz hesaplar için kullanışlıdır.",
    "rateLimitOff": "Kapalı",
    "rateLimitLow": "Düşük (1s)",
    "rateLimitMedium": "Orta (3s)",
    "rateLimitHigh": "Yüksek (6s)",
    "postProcessLabel": "Uzun Satırları Otomatik Düzelt",
    "postProcessTooltip": "Çeviriden sonra, çok uzayan satırları daha iyi okunabilirlik için otomatik olarak ikiye böler. Yalnızca SRT/VTT için geçerlidir.",
    "assFormatNote": "ASS/SSA dosyalarında yalnızca diyalog metni çevrilir - stil, zamanlama ve efektler değiştirilmeden kalır.",
},
"fr": {
    "appTitle": "SubMovies - Traducteur de sous-titres IA",
    "appHeaderTitle": "Traducteur intelligent SubMovies",
    "appSubtitle": "Traduisez vos sous-titres sans effort et avec précision.",
    "apiKeyLabel": "Clé API :",
    "apiKeyPlaceholder": "Entrez votre clé API ici",
    "saveApiKeyLabel": "Enregistrer la clé API",
    "modelLabel": "Modèle IA :",
    "temperatureLabel": "Niveau de créativité :",
    "toneLabel": "Ton de traduction :",
    "langTargetLabel": "Langue cible :",
    "filenameLabel": "Nom du fichier de sortie :",
    "filenamePlaceholder": "ex : MyTranslatedMovie.srt",
    "translateBtn": "Traduire les sous-titres",
    "fileChooseLabel": "Téléverser un fichier .srt, .vtt, .ass ou .ssa :",
    "fileChooseButtonText": "Choisir un fichier",
    "fileNone": "Aucun fichier choisi",
    "charCountLabel": "Caractères : {count}",
    "promptPlaceholder": "Ou collez le texte des sous-titres ici (le format SRT, VTT ou ASS est détecté automatiquement)",
    "downloadBtn": "Télécharger le fichier traduit",
    "copyBtnText": "Copier",
    "copySuccess": "Copié dans le presse-papiers !",
    "copyFail": "Échec de la copie du texte.",
    "translatingPlaceholder": "Traduction en cours... veuillez patienter.",
    "responseTitle": "Comparaison de traduction",
    "originalTitle": "Texte original",
    "translatedTitle": "Texte traduit",
    "themeToggleLight": "Passer au mode clair",
    "themeToggleDark": "Passer au mode sombre",
    "closeBtnLabel": "Fermer",
    "footerMadeWith": "Fait avec",
    "footerBy": "par",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "Fichier SRT invalide. Veuillez vérifier le format.",
    "fileValidationVTTError": "Fichier VTT invalide. En-tête WEBVTT manquant ou format incorrect.",
    "fileValidationASSError": "Fichier ASS/SSA invalide. Impossible de trouver [Script Info], [Events] ou des lignes Dialogue.",
    "unsupportedFileType": "Type de fichier non pris en charge. Veuillez téléverser un fichier .srt, .vtt, .ass ou .ssa.",
    "fileReadError": "Erreur de lecture du fichier. Il est peut-être corrompu ou trop volumineux.",
    "charCountWarning": "Attention : un texte très long peut prendre plus de temps ou atteindre les limites de l'API.",
    "errorMissing": "La clé API et le texte des sous-titres sont requis.",
    "errorAPI": "Erreur API : {message}",
    "errorNetwork": "Erreur réseau. Veuillez vérifier votre connexion internet.",
    "errorUnknown": "Une erreur inconnue s'est produite. Veuillez réessayer.",
    "errorNoDownloadText": "Aucun texte traduit disponible pour le téléchargement.",
    "apiKeyTooltip": "Entrez la clé API du fournisseur sélectionné : depuis Google AI Studio pour Gemini, depuis la plateforme DeepSeek pour DeepSeek, ou depuis la console Anthropic pour Claude. Cette clé n'est utilisée et stockée que pour ce fournisseur.",
    "saveApiKeyTooltip": "Si coché, votre clé API est stockée localement dans votre navigateur. Décochez pour la supprimer.",
    "modelTooltip": "Les modèles IA sont fréquemment mis à jour et retirés. Les modèles marqués d'un * sont généralement plus rapides/économiques mais ont des limites d'utilisation plus strictes. Vérifiez toujours les identifiants exacts et la tarification actuelle sur la documentation officielle : ai.google.dev/gemini-api/docs/models pour Gemini, api-docs.deepseek.com pour DeepSeek, docs.claude.com pour Claude.",
    "temperatureTooltip": "Des valeurs plus basses (ex. 0,2) donnent des traductions plus prévisibles et littérales. Des valeurs plus élevées (ex. 0,9) encouragent plus de créativité et de variété. Par défaut : 0,7",
    "toneTooltip": "Choisissez le style et le ton du dialogue traduit pour correspondre au contexte de votre contenu.",
    "targetLangTooltip": "Choisissez la langue dans laquelle vous souhaitez traduire les sous-titres.",
    "uploadFileTooltip": "Cliquez pour téléverser un fichier de sous-titres (.srt, .vtt, .ass ou .ssa) depuis votre appareil.",
    "outputFileNameTooltip": "Entrez un nom personnalisé pour le fichier traduit. Si laissé vide, un nom sera généré automatiquement.",
    "customPromptLabel": "Instructions personnalisées (optionnel) :",
    "customPromptPlaceholder": "ex : Ne traduis pas les noms des personnages / utilise un ton humoristique / utilise un langage familier...",
    "customPromptTooltip": "Ajoutez toute instruction supplémentaire que le modèle doit suivre pendant la traduction. Ceci s'applique comme guide de style/contexte et ne peut pas outrepasser les règles de formatage SRT/VTT.",
    "stopBtn": "Arrêter la traduction",
    "translatingProgress": "Traduction du segment {current} sur {total}...",
    "translationCancelled": "La traduction a été annulée par l'utilisateur.",
    "manualModeLabel": "Mode traduction manuelle (sans IA)",
    "manualModeTooltip": "Activez ceci pour traduire ligne par ligne vous-même plutôt que d'utiliser l'IA. Le texte original apparaît à gauche ; tapez votre traduction à droite. Tout est enregistré automatiquement.",
    "manualEditorTitle": "Éditeur de traduction manuelle",
    "manualEditorEmptyHint": "Téléversez un fichier de sous-titres ou collez son texte ci-dessus pour commencer.",
    "manualTranslationPlaceholder": "Tapez votre traduction ici...",
    "manualDownloadBtn": "Télécharger le fichier SRT traduit",
    "manualAutoSaveHint": "Tout est enregistré automatiquement dans ce navigateur.",
    "chunkSizeLabel": "Volume de traitement par étape :",
    "chunkSizeTooltip": "Nombre de lignes de sous-titres envoyées au modèle par requête. Une valeur plus faible est plus stable mais nécessite plus de requêtes ; une valeur plus élevée est plus rapide et économique mais augmente légèrement le risque de désynchronisation des lignes.",
    "chunkSizeOptimal": "Optimal (recommandé)",
    "chunkSizeHigh": "Élevé",
    "chunkSizeVeryHigh": "Très élevé",
    "resumeBtn": "Reprendre la traduction",
    "partialTranslationSaved": "{current} sur {total} parties traduites. Cliquez sur \"Reprendre la traduction\" pour continuer à partir d'ici.",
    "rateLimitLabel": "Délai entre les requêtes :",
    "rateLimitTooltip": "Ajoute une pause entre les requêtes consécutives au modèle, réduisant le risque d'atteindre la limite de débit du fournisseur. Utile pour les gros fichiers ou les comptes gratuits.",
    "rateLimitOff": "Désactivé",
    "rateLimitLow": "Faible (1s)",
    "rateLimitMedium": "Moyen (3s)",
    "rateLimitHigh": "Élevé (6s)",
    "postProcessLabel": "Corriger les lignes longues automatiquement",
    "postProcessTooltip": "Après la traduction, divise automatiquement en deux les lignes devenues trop longues, pour une meilleure lisibilité des sous-titres. S'applique uniquement au SRT/VTT.",
    "assFormatNote": "Pour les fichiers ASS/SSA, seul le texte du dialogue est traduit - le style, le minutage et les effets restent inchangés.",
},
"de": {
    "appTitle": "SubMovies - KI-Untertitelübersetzer",
    "appHeaderTitle": "SubMovies KI-Übersetzer",
    "appSubtitle": "Übersetzen Sie Ihre Untertitel mühelos und präzise.",
    "apiKeyLabel": "API-Schlüssel:",
    "apiKeyPlaceholder": "Geben Sie hier Ihren API-Schlüssel ein",
    "saveApiKeyLabel": "API-Schlüssel speichern",
    "modelLabel": "KI-Modell:",
    "temperatureLabel": "Kreativitätsgrad:",
    "toneLabel": "Übersetzungston:",
    "langTargetLabel": "Zielsprache:",
    "filenameLabel": "Ausgabedateiname:",
    "filenamePlaceholder": "z. B. MyTranslatedMovie.srt",
    "translateBtn": "Untertitel übersetzen",
    "fileChooseLabel": ".srt-, .vtt-, .ass- oder .ssa-Datei hochladen:",
    "fileChooseButtonText": "Datei auswählen",
    "fileNone": "Keine Datei ausgewählt",
    "charCountLabel": "Zeichen: {count}",
    "promptPlaceholder": "Oder fügen Sie hier Untertiteltext ein (SRT-, VTT- oder ASS-Format wird automatisch erkannt)",
    "downloadBtn": "Übersetzte Datei herunterladen",
    "copyBtnText": "Kopieren",
    "copySuccess": "In die Zwischenablage kopiert!",
    "copyFail": "Text konnte nicht kopiert werden.",
    "translatingPlaceholder": "Wird übersetzt... bitte warten.",
    "responseTitle": "Übersetzungsvergleich",
    "originalTitle": "Originaltext",
    "translatedTitle": "Übersetzter Text",
    "themeToggleLight": "Zum hellen Modus wechseln",
    "themeToggleDark": "Zum dunklen Modus wechseln",
    "closeBtnLabel": "Schließen",
    "footerMadeWith": "Erstellt mit",
    "footerBy": "von",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "Ungültige SRT-Datei. Bitte überprüfen Sie das Format.",
    "fileValidationVTTError": "Ungültige VTT-Datei. WEBVTT-Header fehlt oder Format ist falsch.",
    "fileValidationASSError": "Ungültige ASS/SSA-Datei. [Script Info], [Events] oder Dialogue-Zeilen nicht gefunden.",
    "unsupportedFileType": "Nicht unterstützter Dateityp. Bitte laden Sie eine .srt-, .vtt-, .ass- oder .ssa-Datei hoch.",
    "fileReadError": "Fehler beim Lesen der Datei. Sie ist möglicherweise beschädigt oder zu groß.",
    "charCountWarning": "Warnung: Sehr langer Text kann länger dauern oder API-Limits erreichen.",
    "errorMissing": "API-Schlüssel und Untertiteltext sind erforderlich.",
    "errorAPI": "API-Fehler: {message}",
    "errorNetwork": "Netzwerkfehler. Bitte überprüfen Sie Ihre Internetverbindung.",
    "errorUnknown": "Ein unbekannter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    "errorNoDownloadText": "Kein übersetzter Text zum Herunterladen verfügbar.",
    "apiKeyTooltip": "Geben Sie den API-Schlüssel für den gewählten Anbieter ein: aus Google AI Studio für Gemini-Modelle, von der DeepSeek-Plattform für DeepSeek-Modelle, oder aus der Anthropic-Konsole für Claude-Modelle. Dieser Schlüssel wird nur für diesen Anbieter verwendet und gespeichert.",
    "saveApiKeyTooltip": "Wenn aktiviert, wird Ihr API-Schlüssel lokal in Ihrem Browser gespeichert. Deaktivieren Sie das Kästchen, um ihn zu entfernen.",
    "modelTooltip": "KI-Modelle werden häufig aktualisiert und eingestellt. Mit * markierte Modelle sind meist schneller/günstiger, haben aber strengere Nutzungslimits. Prüfen Sie immer die genauen Modell-IDs und aktuellen Preise in der offiziellen Dokumentation: ai.google.dev/gemini-api/docs/models für Gemini, api-docs.deepseek.com für DeepSeek, docs.claude.com für Claude.",
    "temperatureTooltip": "Niedrigere Werte (z. B. 0,2) ergeben vorhersehbarere, wörtlichere Übersetzungen. Höhere Werte (z. B. 0,9) fördern mehr Kreativität und Wortvielfalt. Standard: 0,7",
    "toneTooltip": "Wählen Sie Stil und Ton des übersetzten Dialogs passend zum Kontext Ihres Inhalts.",
    "targetLangTooltip": "Wählen Sie die Sprache, in die die Untertitel übersetzt werden sollen.",
    "uploadFileTooltip": "Klicken Sie, um eine Untertiteldatei (.srt, .vtt, .ass oder .ssa) von Ihrem Gerät hochzuladen.",
    "outputFileNameTooltip": "Geben Sie einen benutzerdefinierten Namen für die übersetzte Datei ein. Wenn leer gelassen, wird automatisch ein Name generiert.",
    "customPromptLabel": "Benutzerdefinierte Anweisungen (optional):",
    "customPromptPlaceholder": "z. B. Charakternamen nicht übersetzen / humorvollen Ton verwenden / lockere Alltagssprache verwenden...",
    "customPromptTooltip": "Fügen Sie zusätzliche Anweisungen hinzu, die das Modell beim Übersetzen befolgen soll. Dies wird als zusätzlicher Stil-/Kontexthinweis angewendet und kann die SRT/VTT-Formatierungsregeln nicht außer Kraft setzen.",
    "stopBtn": "Übersetzung stoppen",
    "translatingProgress": "Übersetze Abschnitt {current} von {total}...",
    "translationCancelled": "Die Übersetzung wurde vom Benutzer abgebrochen.",
    "manualModeLabel": "Manueller Übersetzungsmodus (ohne KI)",
    "manualModeTooltip": "Aktivieren Sie dies, um Zeile für Zeile selbst zu übersetzen, statt KI zu verwenden. Der Originaltext erscheint links; tippen Sie Ihre Übersetzung rechts ein. Alles wird automatisch gespeichert.",
    "manualEditorTitle": "Editor für manuelle Übersetzung",
    "manualEditorEmptyHint": "Laden Sie eine Untertiteldatei hoch oder fügen Sie den Text oben ein, um zu beginnen.",
    "manualTranslationPlaceholder": "Geben Sie hier Ihre Übersetzung ein...",
    "manualDownloadBtn": "Übersetzte SRT-Datei herunterladen",
    "manualAutoSaveHint": "Alles wird automatisch in diesem Browser gespeichert.",
    "chunkSizeLabel": "Verarbeitungsumfang pro Schritt:",
    "chunkSizeTooltip": "Wie viele Untertitelzeilen pro Anfrage an das Modell gesendet werden. Ein kleinerer Wert ist stabiler, benötigt aber mehr Anfragen; ein größerer Wert ist schneller und günstiger, erhöht aber leicht das Risiko einer Zeilen-Desynchronisation.",
    "chunkSizeOptimal": "Optimal (empfohlen)",
    "chunkSizeHigh": "Hoch",
    "chunkSizeVeryHigh": "Sehr hoch",
    "resumeBtn": "Übersetzung fortsetzen",
    "partialTranslationSaved": "{current} von {total} Teilen übersetzt. Klicken Sie auf \"Übersetzung fortsetzen\", um von hier aus weiterzumachen.",
    "rateLimitLabel": "Verzögerung zwischen Anfragen:",
    "rateLimitTooltip": "Fügt eine Pause zwischen aufeinanderfolgenden Anfragen an das Modell ein und verringert so das Risiko, das Ratenlimit des Anbieters zu erreichen. Nützlich für große Dateien oder kostenlose Konten.",
    "rateLimitOff": "Aus",
    "rateLimitLow": "Niedrig (1s)",
    "rateLimitMedium": "Mittel (3s)",
    "rateLimitHigh": "Hoch (6s)",
    "postProcessLabel": "Lange Zeilen automatisch korrigieren",
    "postProcessTooltip": "Teilt nach der Übersetzung automatisch zu lang gewordene Zeilen in zwei auf, für bessere Lesbarkeit der Untertitel. Gilt nur für SRT/VTT.",
    "assFormatNote": "Bei ASS/SSA-Dateien wird nur der Dialogtext übersetzt - Stil, Zeitsteuerung und Effekte bleiben unverändert.",
},
"es": {
    "appTitle": "SubMovies - Traductor de subtítulos IA",
    "appHeaderTitle": "Traductor inteligente SubMovies",
    "appSubtitle": "Traduce tus subtítulos sin complicaciones y con precisión.",
    "apiKeyLabel": "Clave API:",
    "apiKeyPlaceholder": "Introduce aquí tu clave API",
    "saveApiKeyLabel": "Guardar clave API",
    "modelLabel": "Modelo de IA:",
    "temperatureLabel": "Nivel de creatividad:",
    "toneLabel": "Tono de traducción:",
    "langTargetLabel": "Idioma de destino:",
    "filenameLabel": "Nombre del archivo de salida:",
    "filenamePlaceholder": "ej: MyTranslatedMovie.srt",
    "translateBtn": "Traducir subtítulos",
    "fileChooseLabel": "Subir archivo .srt, .vtt, .ass o .ssa:",
    "fileChooseButtonText": "Elegir archivo",
    "fileNone": "Ningún archivo seleccionado",
    "charCountLabel": "Caracteres: {count}",
    "promptPlaceholder": "O pega el texto de los subtítulos aquí (el formato SRT, VTT o ASS se detecta automáticamente)",
    "downloadBtn": "Descargar archivo traducido",
    "copyBtnText": "Copiar",
    "copySuccess": "¡Copiado al portapapeles!",
    "copyFail": "Error al copiar el texto.",
    "translatingPlaceholder": "Traduciendo... por favor espera.",
    "responseTitle": "Comparación de traducción",
    "originalTitle": "Texto original",
    "translatedTitle": "Texto traducido",
    "themeToggleLight": "Cambiar a modo claro",
    "themeToggleDark": "Cambiar a modo oscuro",
    "closeBtnLabel": "Cerrar",
    "footerMadeWith": "Hecho con",
    "footerBy": "por",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "Archivo SRT no válido. Verifica el formato.",
    "fileValidationVTTError": "Archivo VTT no válido. Falta el encabezado WEBVTT o el formato es incorrecto.",
    "fileValidationASSError": "Archivo ASS/SSA no válido. No se encontraron [Script Info], [Events] o líneas Dialogue.",
    "unsupportedFileType": "Tipo de archivo no compatible. Sube un archivo .srt, .vtt, .ass o .ssa.",
    "fileReadError": "Error al leer el archivo. Puede estar dañado o ser demasiado grande.",
    "charCountWarning": "Advertencia: un texto muy largo puede tardar más o alcanzar los límites de la API.",
    "errorMissing": "Se requieren la clave API y el texto de los subtítulos.",
    "errorAPI": "Error de la API: {message}",
    "errorNetwork": "Error de red. Verifica tu conexión a internet.",
    "errorUnknown": "Ocurrió un error desconocido. Inténtalo de nuevo.",
    "errorNoDownloadText": "No hay texto traducido disponible para descargar.",
    "apiKeyTooltip": "Introduce la clave API del proveedor seleccionado: desde Google AI Studio para Gemini, desde la plataforma DeepSeek para DeepSeek, o desde la consola de Anthropic para Claude. Esta clave solo se usa y almacena para ese proveedor.",
    "saveApiKeyTooltip": "Si está marcado, tu clave API se guarda localmente en tu navegador. Desmarca para eliminarla.",
    "modelTooltip": "Los modelos de IA se actualizan y retiran con frecuencia. Los modelos marcados con * suelen ser más rápidos/económicos pero tienen límites de uso más estrictos. Consulta siempre los ID exactos y los precios actuales en la documentación oficial: ai.google.dev/gemini-api/docs/models para Gemini, api-docs.deepseek.com para DeepSeek, docs.claude.com para Claude.",
    "temperatureTooltip": "Valores más bajos (ej. 0.2) dan traducciones más predecibles y literales. Valores más altos (ej. 0.9) fomentan más creatividad y variedad de palabras. Predeterminado: 0.7",
    "toneTooltip": "Elige el estilo y tono del diálogo traducido para que coincida con el contexto de tu contenido.",
    "targetLangTooltip": "Elige el idioma al que quieres traducir los subtítulos.",
    "uploadFileTooltip": "Haz clic para subir un archivo de subtítulos (.srt, .vtt, .ass o .ssa) desde tu dispositivo.",
    "outputFileNameTooltip": "Introduce un nombre personalizado para el archivo traducido. Si se deja vacío, se generará un nombre automáticamente.",
    "customPromptLabel": "Instrucciones personalizadas (opcional):",
    "customPromptPlaceholder": "ej: No traduzcas los nombres de los personajes / usa un tono humorístico / usa un lenguaje coloquial...",
    "customPromptTooltip": "Añade cualquier instrucción adicional que quieras que el modelo siga al traducir. Se aplica como guía extra de estilo/contexto y no puede anular las reglas de formato SRT/VTT.",
    "stopBtn": "Detener traducción",
    "translatingProgress": "Traduciendo bloque {current} de {total}...",
    "translationCancelled": "La traducción fue cancelada por el usuario.",
    "manualModeLabel": "Modo de traducción manual (sin IA)",
    "manualModeTooltip": "Activa esto para traducir línea por línea tú mismo en lugar de usar IA. El texto original aparece a la izquierda; escribe tu traducción a la derecha. Todo se guarda automáticamente.",
    "manualEditorTitle": "Editor de traducción manual",
    "manualEditorEmptyHint": "Sube un archivo de subtítulos o pega su texto arriba para empezar.",
    "manualTranslationPlaceholder": "Escribe tu traducción aquí...",
    "manualDownloadBtn": "Descargar archivo SRT traducido",
    "manualAutoSaveHint": "Todo se guarda automáticamente en este navegador.",
    "chunkSizeLabel": "Volumen de procesamiento por paso:",
    "chunkSizeTooltip": "Cuántas líneas de subtítulos se envían al modelo por solicitud. Un valor menor es más estable pero requiere más solicitudes; un valor mayor es más rápido y económico pero aumenta ligeramente el riesgo de desincronización de líneas.",
    "chunkSizeOptimal": "Óptimo (recomendado)",
    "chunkSizeHigh": "Alto",
    "chunkSizeVeryHigh": "Muy alto",
    "resumeBtn": "Reanudar traducción",
    "partialTranslationSaved": "{current} de {total} partes traducidas. Haz clic en \"Reanudar traducción\" para continuar desde aquí.",
    "rateLimitLabel": "Retraso entre solicitudes:",
    "rateLimitTooltip": "Añade una pausa entre solicitudes consecutivas al modelo, reduciendo la probabilidad de alcanzar el límite de velocidad del proveedor. Útil para archivos grandes o cuentas gratuitas.",
    "rateLimitOff": "Desactivado",
    "rateLimitLow": "Bajo (1s)",
    "rateLimitMedium": "Medio (3s)",
    "rateLimitHigh": "Alto (6s)",
    "postProcessLabel": "Corregir líneas largas automáticamente",
    "postProcessTooltip": "Después de traducir, divide automáticamente en dos las líneas que quedaron demasiado largas, para mejor legibilidad de los subtítulos. Solo se aplica a SRT/VTT.",
    "assFormatNote": "Para archivos ASS/SSA, solo se traduce el texto del diálogo - el estilo, el tiempo y los efectos quedan intactos.",
},
"ru": {
    "appTitle": "SubMovies - ИИ-переводчик субтитров",
    "appHeaderTitle": "Умный переводчик SubMovies",
    "appSubtitle": "Переводите субтитры без хлопот и с точностью.",
    "apiKeyLabel": "API-ключ:",
    "apiKeyPlaceholder": "Введите здесь ваш API-ключ",
    "saveApiKeyLabel": "Сохранить API-ключ",
    "modelLabel": "Модель ИИ:",
    "temperatureLabel": "Уровень креативности:",
    "toneLabel": "Тон перевода:",
    "langTargetLabel": "Язык перевода:",
    "filenameLabel": "Имя выходного файла:",
    "filenamePlaceholder": "напр.: MyTranslatedMovie.srt",
    "translateBtn": "Перевести субтитры",
    "fileChooseLabel": "Загрузить файл .srt, .vtt, .ass или .ssa:",
    "fileChooseButtonText": "Выбрать файл",
    "fileNone": "Файл не выбран",
    "charCountLabel": "Символов: {count}",
    "promptPlaceholder": "Или вставьте текст субтитров сюда (формат SRT, VTT или ASS определяется автоматически)",
    "downloadBtn": "Скачать переведённый файл",
    "copyBtnText": "Копировать",
    "copySuccess": "Скопировано в буфер обмена!",
    "copyFail": "Не удалось скопировать текст.",
    "translatingPlaceholder": "Идёт перевод... пожалуйста, подождите.",
    "responseTitle": "Сравнение перевода",
    "originalTitle": "Исходный текст",
    "translatedTitle": "Переведённый текст",
    "themeToggleLight": "Переключить на светлую тему",
    "themeToggleDark": "Переключить на тёмную тему",
    "closeBtnLabel": "Закрыть",
    "footerMadeWith": "Сделано с",
    "footerBy": "автор:",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "Недопустимый файл SRT. Проверьте формат.",
    "fileValidationVTTError": "Недопустимый файл VTT. Отсутствует заголовок WEBVTT или неверный формат.",
    "fileValidationASSError": "Недопустимый файл ASS/SSA. Не найдены [Script Info], [Events] или строки Dialogue.",
    "unsupportedFileType": "Неподдерживаемый тип файла. Загрузите файл .srt, .vtt, .ass или .ssa.",
    "fileReadError": "Ошибка чтения файла. Возможно, он повреждён или слишком большой.",
    "charCountWarning": "Внимание: очень длинный текст может занять больше времени или превысить лимиты API.",
    "errorMissing": "Требуются API-ключ и текст субтитров.",
    "errorAPI": "Ошибка API: {message}",
    "errorNetwork": "Ошибка сети. Проверьте подключение к интернету.",
    "errorUnknown": "Произошла неизвестная ошибка. Попробуйте снова.",
    "errorNoDownloadText": "Нет переведённого текста для скачивания.",
    "apiKeyTooltip": "Введите API-ключ для выбранного провайдера: из Google AI Studio для моделей Gemini, с платформы DeepSeek для моделей DeepSeek, или из консоли Anthropic для моделей Claude. Этот ключ используется и хранится только для этого провайдера.",
    "saveApiKeyTooltip": "Если отмечено, ваш API-ключ сохраняется локально в браузере. Снимите отметку, чтобы удалить его.",
    "modelTooltip": "Модели ИИ часто обновляются и снимаются с поддержки. Модели с пометкой * обычно быстрее/дешевле, но имеют более строгие лимиты использования. Всегда проверяйте точные ID моделей и актуальные цены в официальной документации: ai.google.dev/gemini-api/docs/models для Gemini, api-docs.deepseek.com для DeepSeek, docs.claude.com для Claude.",
    "temperatureTooltip": "Более низкие значения (напр. 0,2) дают более предсказуемый, дословный перевод. Более высокие значения (напр. 0,9) поощряют больше креативности и разнообразия слов. По умолчанию: 0,7",
    "toneTooltip": "Выберите стиль и тон переведённого диалога, соответствующие контексту вашего контента.",
    "targetLangTooltip": "Выберите язык, на который вы хотите перевести субтитры.",
    "uploadFileTooltip": "Нажмите, чтобы загрузить файл субтитров (.srt, .vtt, .ass или .ssa) с вашего устройства.",
    "outputFileNameTooltip": "Введите произвольное имя для переведённого файла. Если оставить пустым, имя будет создано автоматически.",
    "customPromptLabel": "Дополнительные инструкции (необязательно):",
    "customPromptPlaceholder": "например: не переводи имена персонажей / используй юмористический тон / используй разговорную лексику...",
    "customPromptTooltip": "Добавьте любые дополнительные инструкции, которым должна следовать модель при переводе. Это применяется как дополнительное указание по стилю/контексту и не может отменить правила форматирования SRT/VTT.",
    "stopBtn": "Остановить перевод",
    "translatingProgress": "Перевод части {current} из {total}...",
    "translationCancelled": "Перевод был отменён пользователем.",
    "manualModeLabel": "Режим ручного перевода (без ИИ)",
    "manualModeTooltip": "Включите это, чтобы переводить построчно самостоятельно вместо использования ИИ. Исходный текст отображается слева; вводите перевод справа. Всё сохраняется автоматически.",
    "manualEditorTitle": "Редактор ручного перевода",
    "manualEditorEmptyHint": "Загрузите файл субтитров или вставьте его текст выше, чтобы начать.",
    "manualTranslationPlaceholder": "Введите здесь свой перевод...",
    "manualDownloadBtn": "Скачать переведённый файл SRT",
    "manualAutoSaveHint": "Всё сохраняется автоматически в этом браузере.",
    "chunkSizeLabel": "Объём обработки за один шаг:",
    "chunkSizeTooltip": "Сколько строк субтитров отправляется модели за один запрос. Меньшее значение стабильнее, но требует больше запросов; большее значение быстрее и дешевле, но немного повышает риск рассинхронизации строк.",
    "chunkSizeOptimal": "Оптимально (рекомендуется)",
    "chunkSizeHigh": "Высокий",
    "chunkSizeVeryHigh": "Очень высокий",
    "resumeBtn": "Продолжить перевод",
    "partialTranslationSaved": "Переведено {current} из {total} частей. Нажмите «Продолжить перевод», чтобы продолжить отсюда.",
    "rateLimitLabel": "Задержка между запросами:",
    "rateLimitTooltip": "Добавляет паузу между последовательными запросами к модели, снижая риск достижения лимита запросов провайдера. Полезно для больших файлов или бесплатных аккаунтов.",
    "rateLimitOff": "Выключено",
    "rateLimitLow": "Низкая (1с)",
    "rateLimitMedium": "Средняя (3с)",
    "rateLimitHigh": "Высокая (6с)",
    "postProcessLabel": "Автоисправление длинных строк",
    "postProcessTooltip": "После перевода автоматически разбивает слишком длинные строки на две для лучшей читаемости субтитров. Применяется только к SRT/VTT.",
    "assFormatNote": "Для файлов ASS/SSA переводится только текст диалогов - стиль, тайминг и эффекты остаются без изменений.",
},
"zh": {
    "appTitle": "SubMovies - AI 字幕翻译器",
    "appHeaderTitle": "SubMovies 智能翻译器",
    "appSubtitle": "轻松、精准地翻译您的字幕。",
    "apiKeyLabel": "API 密钥：",
    "apiKeyPlaceholder": "在此输入您的 API 密钥",
    "saveApiKeyLabel": "保存 API 密钥",
    "modelLabel": "AI 模型：",
    "temperatureLabel": "创意程度：",
    "toneLabel": "翻译语气：",
    "langTargetLabel": "目标语言：",
    "filenameLabel": "输出文件名：",
    "filenamePlaceholder": "例如：MyTranslatedMovie.srt",
    "translateBtn": "翻译字幕",
    "fileChooseLabel": "上传 .srt、.vtt、.ass 或 .ssa 文件：",
    "fileChooseButtonText": "选择文件",
    "fileNone": "未选择文件",
    "charCountLabel": "字符数：{count}",
    "promptPlaceholder": "或在此粘贴字幕文本（自动识别 SRT、VTT 或 ASS 格式）",
    "downloadBtn": "下载翻译文件",
    "copyBtnText": "复制",
    "copySuccess": "已复制到剪贴板！",
    "copyFail": "复制文本失败。",
    "translatingPlaceholder": "翻译中……请稍候。",
    "responseTitle": "翻译对比",
    "originalTitle": "原文",
    "translatedTitle": "译文",
    "themeToggleLight": "切换到浅色模式",
    "themeToggleDark": "切换到深色模式",
    "closeBtnLabel": "关闭",
    "footerMadeWith": "使用",
    "footerBy": "制作，作者：",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "SRT 文件无效，请检查格式。",
    "fileValidationVTTError": "VTT 文件无效，缺少 WEBVTT 头或格式错误。",
    "fileValidationASSError": "ASS/SSA 文件无效，找不到 [Script Info]、[Events] 或 Dialogue 行。",
    "unsupportedFileType": "不支持的文件类型，请上传 .srt、.vtt、.ass 或 .ssa 文件。",
    "fileReadError": "读取文件时出错，文件可能已损坏或过大。",
    "charCountWarning": "警告：文本过长可能需要更长时间或触发 API 限制。",
    "errorMissing": "需要提供 API 密钥和字幕文本。",
    "errorAPI": "API 错误：{message}",
    "errorNetwork": "网络错误，请检查您的互联网连接。",
    "errorUnknown": "发生未知错误，请重试。",
    "errorNoDownloadText": "没有可供下载的翻译文本。",
    "apiKeyTooltip": "请输入所选服务商的 API 密钥：Gemini 模型请使用 Google AI Studio 的密钥，DeepSeek 模型请使用 DeepSeek 平台的密钥，Claude 模型请使用 Anthropic 控制台的密钥。该密钥仅用于并保存给对应的服务商。",
    "saveApiKeyTooltip": "勾选后，您的 API 密钥将安全地保存在浏览器本地。取消勾选可将其删除。",
    "modelTooltip": "AI 模型会经常更新和下线。带 * 标记的模型通常更快/更便宜，但使用限制更严格。请始终在官方文档中核实准确的模型 ID 和当前价格：Gemini 请查看 ai.google.dev/gemini-api/docs/models，DeepSeek 请查看 api-docs.deepseek.com，Claude 请查看 docs.claude.com。",
    "temperatureTooltip": "较低的值（如 0.2）会产生更可预测、更直译的翻译。较高的值（如 0.9）会鼓励更多创意和用词多样性。默认值：0.7",
    "toneTooltip": "选择翻译对话的风格和语气，以匹配您内容的语境。",
    "targetLangTooltip": "选择您希望将字幕翻译成的语言。",
    "uploadFileTooltip": "点击从您的设备上传字幕文件（.srt、.vtt、.ass 或 .ssa）。",
    "outputFileNameTooltip": "为翻译文件输入自定义名称。如留空，将自动生成名称。",
    "customPromptLabel": "自定义指令（可选）：",
    "customPromptPlaceholder": "例如：不要翻译角色名字 / 使用幽默的语气 / 使用日常口语化的措辞……",
    "customPromptTooltip": "添加您希望模型在翻译时遵循的任何额外指令。这将作为额外的风格/语境指导应用，且不能覆盖 SRT/VTT 格式规则。",
    "stopBtn": "停止翻译",
    "translatingProgress": "正在翻译第 {current} / {total} 块...",
    "translationCancelled": "翻译已被用户取消。",
    "manualModeLabel": "手动翻译模式（不使用 AI）",
    "manualModeTooltip": "开启此模式后，您可以自己逐行翻译，而不是使用 AI。原文显示在左侧；请在右侧输入您的翻译。所有内容都会自动保存。",
    "manualEditorTitle": "手动翻译编辑器",
    "manualEditorEmptyHint": "请上传字幕文件或在上方粘贴文本以开始。",
    "manualTranslationPlaceholder": "在此输入您的翻译……",
    "manualDownloadBtn": "下载翻译好的 SRT 文件",
    "manualAutoSaveHint": "所有内容都会自动保存在此浏览器中。",
    "chunkSizeLabel": "每步处理量：",
    "chunkSizeTooltip": "每次请求发送给模型的字幕行数。较小的值更稳定，但需要更多请求；较大的值更快更省钱，但会略微增加行错位的风险。",
    "chunkSizeOptimal": "最佳（推荐）",
    "chunkSizeHigh": "较大",
    "chunkSizeVeryHigh": "非常大",
    "resumeBtn": "继续翻译",
    "partialTranslationSaved": "已翻译 {total} 个部分中的 {current} 个。点击“继续翻译”从此处继续。",
    "rateLimitLabel": "请求间延迟：",
    "rateLimitTooltip": "在连续请求模型之间添加暂停，降低触发服务商速率限制的可能性。适用于大文件或免费账户。",
    "rateLimitOff": "关闭",
    "rateLimitLow": "低（1秒）",
    "rateLimitMedium": "中（3秒）",
    "rateLimitHigh": "高（6秒）",
    "postProcessLabel": "自动修正过长行",
    "postProcessTooltip": "翻译后自动将过长的行拆分为两行，以提升字幕可读性。仅适用于 SRT/VTT。",
    "assFormatNote": "对于 ASS/SSA 文件，只翻译对话文本——样式、时间轴和特效保持不变。",
},
"hi": {
    "appTitle": "SubMovies - एआई सबटाइटल अनुवादक",
    "appHeaderTitle": "SubMovies स्मार्ट अनुवादक",
    "appSubtitle": "अपनी सबटाइटल फ़ाइलों का आसान और सटीक अनुवाद करें।",
    "apiKeyLabel": "API कुंजी:",
    "apiKeyPlaceholder": "अपनी API कुंजी यहाँ दर्ज करें",
    "saveApiKeyLabel": "API कुंजी सहेजें",
    "modelLabel": "एआई मॉडल:",
    "temperatureLabel": "रचनात्मकता स्तर:",
    "toneLabel": "अनुवाद का लहजा:",
    "langTargetLabel": "लक्ष्य भाषा:",
    "filenameLabel": "आउटपुट फ़ाइल नाम:",
    "filenamePlaceholder": "उदाहरण: MyTranslatedMovie.srt",
    "translateBtn": "सबटाइटल अनुवाद करें",
    "fileChooseLabel": ".srt, .vtt, .ass या .ssa फ़ाइल अपलोड करें:",
    "fileChooseButtonText": "फ़ाइल चुनें",
    "fileNone": "कोई फ़ाइल नहीं चुनी गई",
    "charCountLabel": "अक्षर: {count}",
    "promptPlaceholder": "या यहाँ सबटाइटल टेक्स्ट पेस्ट करें (SRT, VTT या ASS फॉर्मेट अपने आप पहचाना जाएगा)",
    "downloadBtn": "अनुवादित फ़ाइल डाउनलोड करें",
    "copyBtnText": "कॉपी करें",
    "copySuccess": "क्लिपबोर्ड पर कॉपी हो गया!",
    "copyFail": "टेक्स्ट कॉपी करने में विफल।",
    "translatingPlaceholder": "अनुवाद हो रहा है... कृपया प्रतीक्षा करें।",
    "responseTitle": "अनुवाद तुलना",
    "originalTitle": "मूल टेक्स्ट",
    "translatedTitle": "अनुवादित टेक्स्ट",
    "themeToggleLight": "लाइट मोड में बदलें",
    "themeToggleDark": "डार्क मोड में बदलें",
    "closeBtnLabel": "बंद करें",
    "footerMadeWith": "इसके साथ बनाया गया",
    "footerBy": "द्वारा",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "अमान्य SRT फ़ाइल। कृपया फॉर्मेट जाँचें।",
    "fileValidationVTTError": "अमान्य VTT फ़ाइल। WEBVTT हेडर गायब है या फॉर्मेट गलत है।",
    "fileValidationASSError": "अमान्य ASS/SSA फ़ाइल। [Script Info], [Events] या Dialogue लाइनें नहीं मिलीं।",
    "unsupportedFileType": "असमर्थित फ़ाइल प्रकार। कृपया .srt, .vtt, .ass या .ssa फ़ाइल अपलोड करें।",
    "fileReadError": "फ़ाइल पढ़ने में त्रुटि। यह खराब या बहुत बड़ी हो सकती है।",
    "charCountWarning": "चेतावनी: बहुत लंबा टेक्स्ट अधिक समय ले सकता है या API सीमाओं से टकरा सकता है।",
    "errorMissing": "API कुंजी और सबटाइटल टेक्स्ट आवश्यक हैं।",
    "errorAPI": "API त्रुटि: {message}",
    "errorNetwork": "नेटवर्क त्रुटि। कृपया अपना इंटरनेट कनेक्शन जाँचें।",
    "errorUnknown": "एक अज्ञात त्रुटि हुई। कृपया पुनः प्रयास करें।",
    "errorNoDownloadText": "डाउनलोड के लिए कोई अनुवादित टेक्स्ट उपलब्ध नहीं है।",
    "apiKeyTooltip": "चुने गए प्रदाता की API कुंजी दर्ज करें: Gemini मॉडल के लिए Google AI Studio से, DeepSeek मॉडल के लिए DeepSeek प्लेटफ़ॉर्म से, या Claude मॉडल के लिए Anthropic कंसोल से। यह कुंजी केवल उसी प्रदाता के लिए उपयोग और सहेजी जाती है।",
    "saveApiKeyTooltip": "यदि चेक किया गया, तो आपकी API कुंजी आपके ब्राउज़र में स्थानीय रूप से सहेजी जाएगी। हटाने के लिए अनचेक करें।",
    "modelTooltip": "एआई मॉडल अक्सर अपडेट और बंद किए जाते हैं। * चिह्नित मॉडल आमतौर पर तेज़/सस्ते होते हैं लेकिन उपयोग सीमाएँ सख्त होती हैं। हमेशा आधिकारिक दस्तावेज़ों से सटीक मॉडल ID और मूल्य जाँचें: Gemini के लिए ai.google.dev/gemini-api/docs/models, DeepSeek के लिए api-docs.deepseek.com, Claude के लिए docs.claude.com।",
    "temperatureTooltip": "कम मान (जैसे 0.2) अधिक पूर्वानुमानित, शाब्दिक अनुवाद देते हैं। अधिक मान (जैसे 0.9) अधिक रचनात्मकता और शब्द विविधता को बढ़ावा देते हैं। डिफ़ॉल्ट: 0.7",
    "toneTooltip": "आपकी सामग्री के संदर्भ से मेल खाने के लिए अनुवादित संवाद की शैली और लहजा चुनें।",
    "targetLangTooltip": "वह भाषा चुनें जिसमें आप सबटाइटल का अनुवाद करवाना चाहते हैं।",
    "uploadFileTooltip": "अपने डिवाइस से सबटाइटल फ़ाइल (.srt, .vtt, .ass या .ssa) अपलोड करने के लिए क्लिक करें।",
    "outputFileNameTooltip": "अनुवादित फ़ाइल के लिए एक कस्टम नाम दर्ज करें। खाली छोड़ने पर, नाम अपने आप बन जाएगा।",
    "customPromptLabel": "कस्टम निर्देश (वैकल्पिक):",
    "customPromptPlaceholder": "जैसे: पात्रों के नाम अनुवाद न करें / हास्यपूर्ण लहजा रखें / रोज़मर्रा की बोलचाल की भाषा इस्तेमाल करें...",
    "customPromptTooltip": "अनुवाद के दौरान मॉडल को किन अतिरिक्त निर्देशों का पालन करना है, वह यहाँ जोड़ें। यह अतिरिक्त शैली/संदर्भ मार्गदर्शन के रूप में लागू होता है और SRT/VTT फॉर्मेटिंग नियमों को ओवरराइड नहीं कर सकता।",
    "stopBtn": "अनुवाद रोकें",
    "translatingProgress": "{total} में से {current} भाग का अनुवाद हो रहा है...",
    "translationCancelled": "उपयोगकर्ता द्वारा अनुवाद रद्द कर दिया गया।",
    "manualModeLabel": "मैन्युअल अनुवाद मोड (बिना एआई के)",
    "manualModeTooltip": "एआई का उपयोग करने के बजाय खुद लाइन-दर-लाइन अनुवाद करने के लिए इसे चालू करें। मूल टेक्स्ट बाईं ओर दिखाई देगा; अपना अनुवाद दाईं ओर टाइप करें। सब कुछ अपने आप सहेजा जाता है।",
    "manualEditorTitle": "मैन्युअल अनुवाद संपादक",
    "manualEditorEmptyHint": "शुरू करने के लिए ऊपर एक सबटाइटल फ़ाइल अपलोड करें या उसका टेक्स्ट पेस्ट करें।",
    "manualTranslationPlaceholder": "अपना अनुवाद यहाँ लिखें...",
    "manualDownloadBtn": "अनुवादित SRT फ़ाइल डाउनलोड करें",
    "manualAutoSaveHint": "सब कुछ इस ब्राउज़र में अपने आप सहेजा जाता है।",
    "chunkSizeLabel": "प्रति चरण प्रोसेसिंग मात्रा:",
    "chunkSizeTooltip": "हर अनुरोध में मॉडल को कितनी सबटाइटल लाइनें भेजी जाती हैं। कम मान अधिक स्थिर होता है लेकिन ज़्यादा अनुरोधों की ज़रूरत होती है; ज़्यादा मान तेज़ और सस्ता होता है लेकिन लाइनों के क्रम बिगड़ने का जोखिम थोड़ा बढ़ जाता है।",
    "chunkSizeOptimal": "इष्टतम (अनुशंसित)",
    "chunkSizeHigh": "अधिक",
    "chunkSizeVeryHigh": "बहुत अधिक",
    "resumeBtn": "अनुवाद जारी रखें",
    "partialTranslationSaved": "{total} में से {current} भाग अनुवादित हुए। यहाँ से जारी रखने के लिए \"अनुवाद जारी रखें\" पर क्लिक करें।",
    "rateLimitLabel": "अनुरोधों के बीच देरी:",
    "rateLimitTooltip": "मॉडल को लगातार भेजे जाने वाले अनुरोधों के बीच एक ठहराव जोड़ता है, जिससे प्रदाता की दर सीमा (rate limit) से टकराने की संभावना कम हो जाती है। बड़ी फ़ाइलों या मुफ़्त खातों के लिए उपयोगी।",
    "rateLimitOff": "बंद",
    "rateLimitLow": "कम (1 सेकंड)",
    "rateLimitMedium": "मध्यम (3 सेकंड)",
    "rateLimitHigh": "अधिक (6 सेकंड)",
    "postProcessLabel": "लंबी लाइनों को अपने आप ठीक करें",
    "postProcessTooltip": "अनुवाद के बाद, बहुत लंबी हो चुकी लाइनों को अपने आप दो भागों में बाँट देता है ताकि सबटाइटल पढ़ने में आसान रहे। यह केवल SRT/VTT पर लागू होता है।",
    "assFormatNote": "ASS/SSA फ़ाइलों के लिए केवल संवाद टेक्स्ट का अनुवाद होता है - स्टाइल, टाइमिंग और इफ़ेक्ट्स जस के तस रहते हैं।",
},
"ja": {
    "appTitle": "SubMovies - AI字幕翻訳ツール",
    "appHeaderTitle": "SubMovies スマート翻訳",
    "appSubtitle": "字幕を手間なく、正確に翻訳します。",
    "apiKeyLabel": "APIキー：",
    "apiKeyPlaceholder": "ここにAPIキーを入力してください",
    "saveApiKeyLabel": "APIキーを保存",
    "modelLabel": "AIモデル：",
    "temperatureLabel": "創造性レベル：",
    "toneLabel": "翻訳のトーン：",
    "langTargetLabel": "翻訳先言語：",
    "filenameLabel": "出力ファイル名：",
    "filenamePlaceholder": "例：MyTranslatedMovie.srt",
    "translateBtn": "字幕を翻訳",
    "fileChooseLabel": ".srt、.vtt、.ass、.ssaファイルをアップロード：",
    "fileChooseButtonText": "ファイルを選択",
    "fileNone": "ファイルが選択されていません",
    "charCountLabel": "文字数：{count}",
    "promptPlaceholder": "またはここに字幕テキストを貼り付け（SRT、VTT、ASS形式は自動検出されます）",
    "downloadBtn": "翻訳済みファイルをダウンロード",
    "copyBtnText": "コピー",
    "copySuccess": "クリップボードにコピーしました！",
    "copyFail": "テキストのコピーに失敗しました。",
    "translatingPlaceholder": "翻訳中…お待ちください。",
    "responseTitle": "翻訳比較",
    "originalTitle": "原文",
    "translatedTitle": "翻訳文",
    "themeToggleLight": "ライトモードに切り替え",
    "themeToggleDark": "ダークモードに切り替え",
    "closeBtnLabel": "閉じる",
    "footerMadeWith": "制作：",
    "footerBy": "作者：",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "無効なSRTファイルです。形式を確認してください。",
    "fileValidationVTTError": "無効なVTTファイルです。WEBVTTヘッダーがないか、形式が間違っています。",
    "fileValidationASSError": "無効なASS/SSAファイルです。[Script Info]、[Events]、またはDialogue行が見つかりません。",
    "unsupportedFileType": "サポートされていないファイル形式です。.srt、.vtt、.ass、.ssaファイルをアップロードしてください。",
    "fileReadError": "ファイルの読み込みエラーです。破損しているか大きすぎる可能性があります。",
    "charCountWarning": "警告：非常に長いテキストは時間がかかるか、API制限に達する場合があります。",
    "errorMissing": "APIキーと字幕テキストが必要です。",
    "errorAPI": "APIエラー：{message}",
    "errorNetwork": "ネットワークエラーです。インターネット接続を確認してください。",
    "errorUnknown": "不明なエラーが発生しました。もう一度お試しください。",
    "errorNoDownloadText": "ダウンロード可能な翻訳テキストがありません。",
    "apiKeyTooltip": "選択したプロバイダーのAPIキーを入力してください：GeminiモデルはGoogle AI Studioから、DeepSeekモデルはDeepSeekプラットフォームから、ClaudeモデルはAnthropicコンソールから取得します。このキーはそのプロバイダーにのみ使用・保存されます。",
    "saveApiKeyTooltip": "チェックすると、APIキーはブラウザにローカル保存されます。削除するにはチェックを外してください。",
    "modelTooltip": "AIモデルは頻繁に更新・廃止されます。*印のモデルは通常より高速・低コストですが、利用制限が厳しくなります。正確なモデルIDと現在の料金は、必ず公式ドキュメントでご確認ください：Geminiはai.google.dev/gemini-api/docs/models、DeepSeekはapi-docs.deepseek.com、Claudeはdocs.claude.com。",
    "temperatureTooltip": "値を低くする（例：0.2）と、より予測可能で直訳的な翻訳になります。値を高くする（例：0.9）と、より創造的で多様な表現になります。デフォルト：0.7",
    "toneTooltip": "コンテンツの文脈に合わせて、翻訳された対話のスタイルとトーンを選択してください。",
    "targetLangTooltip": "字幕を翻訳したい言語を選択してください。",
    "uploadFileTooltip": "クリックしてデバイスから字幕ファイル（.srt、.vtt、.ass、.ssa）をアップロードします。",
    "outputFileNameTooltip": "翻訳ファイルのカスタム名を入力してください。空欄の場合は自動的に名前が生成されます。",
    "customPromptLabel": "カスタム指示（任意）：",
    "customPromptPlaceholder": "例：キャラクター名は翻訳しない／ユーモラスなトーンにする／日常的な口語表現を使う…",
    "customPromptTooltip": "翻訳時にモデルに従わせたい追加指示を入力してください。これは追加のスタイル/文脈ガイドとして適用され、SRT/VTTの書式ルールを上書きすることはできません。",
    "stopBtn": "翻訳を停止",
    "translatingProgress": "{total}個中{current}個目のブロックを翻訳中...",
    "translationCancelled": "翻訳はユーザーによってキャンセルされました。",
    "manualModeLabel": "手動翻訳モード（AIなし）",
    "manualModeTooltip": "AIを使う代わりに自分で1行ずつ翻訳するには、これをオンにしてください。左側に原文が表示されます。右側に翻訳を入力してください。すべて自動的に保存されます。",
    "manualEditorTitle": "手動翻訳エディター",
    "manualEditorEmptyHint": "開始するには、字幕ファイルをアップロードするか、上のテキストを貼り付けてください。",
    "manualTranslationPlaceholder": "ここに翻訳を入力してください...",
    "manualDownloadBtn": "翻訳済みSRTファイルをダウンロード",
    "manualAutoSaveHint": "すべてこのブラウザに自動的に保存されます。",
    "chunkSizeLabel": "ステップごとの処理量：",
    "chunkSizeTooltip": "1回のリクエストでモデルに送信される字幕行数です。小さい値はより安定していますが、リクエスト数が増えます。大きい値は高速で低コストですが、行のずれのリスクがわずかに高まります。",
    "chunkSizeOptimal": "最適（推奨）",
    "chunkSizeHigh": "多い",
    "chunkSizeVeryHigh": "非常に多い",
    "resumeBtn": "翻訳を再開",
    "partialTranslationSaved": "{total}個中{current}個の部分が翻訳されました。ここから続けるには「翻訳を再開」をクリックしてください。",
    "rateLimitLabel": "リクエスト間の遅延：",
    "rateLimitTooltip": "モデルへの連続したリクエストの間に一時停止を追加し、プロバイダーのレート制限に達する可能性を減らします。大きなファイルや無料プランのアカウントに便利です。",
    "rateLimitOff": "オフ",
    "rateLimitLow": "低（1秒）",
    "rateLimitMedium": "中（3秒）",
    "rateLimitHigh": "高（6秒）",
    "postProcessLabel": "長い行を自動修正",
    "postProcessTooltip": "翻訳後、長くなりすぎた行を自動的に2行に分割し、字幕の読みやすさを向上させます。SRT/VTTのみに適用されます。",
    "assFormatNote": "ASS/SSAファイルでは、対話テキストのみが翻訳されます - スタイル、タイミング、エフェクトはそのまま残ります。",
},
"pt": {
    "appTitle": "SubMovies - Tradutor de Legendas com IA",
    "appHeaderTitle": "Tradutor Inteligente SubMovies",
    "appSubtitle": "Traduza suas legendas sem complicações e com precisão.",
    "apiKeyLabel": "Chave da API:",
    "apiKeyPlaceholder": "Digite sua chave da API aqui",
    "saveApiKeyLabel": "Salvar chave da API",
    "modelLabel": "Modelo de IA:",
    "temperatureLabel": "Nível de criatividade:",
    "toneLabel": "Tom da tradução:",
    "langTargetLabel": "Idioma de destino:",
    "filenameLabel": "Nome do arquivo de saída:",
    "filenamePlaceholder": "ex: MyTranslatedMovie.srt",
    "translateBtn": "Traduzir legendas",
    "fileChooseLabel": "Enviar arquivo .srt, .vtt, .ass ou .ssa:",
    "fileChooseButtonText": "Escolher arquivo",
    "fileNone": "Nenhum arquivo escolhido",
    "charCountLabel": "Caracteres: {count}",
    "promptPlaceholder": "Ou cole o texto da legenda aqui (o formato SRT, VTT ou ASS é detectado automaticamente)",
    "downloadBtn": "Baixar arquivo traduzido",
    "copyBtnText": "Copiar",
    "copySuccess": "Copiado para a área de transferência!",
    "copyFail": "Falha ao copiar o texto.",
    "translatingPlaceholder": "Traduzindo... aguarde.",
    "responseTitle": "Comparação da tradução",
    "originalTitle": "Texto original",
    "translatedTitle": "Texto traduzido",
    "themeToggleLight": "Mudar para modo claro",
    "themeToggleDark": "Mudar para modo escuro",
    "closeBtnLabel": "Fechar",
    "footerMadeWith": "Feito com",
    "footerBy": "por",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "Arquivo SRT inválido. Verifique o formato.",
    "fileValidationVTTError": "Arquivo VTT inválido. Cabeçalho WEBVTT ausente ou formato incorreto.",
    "fileValidationASSError": "Arquivo ASS/SSA inválido. Não foi possível encontrar [Script Info], [Events] ou linhas Dialogue.",
    "unsupportedFileType": "Tipo de arquivo não suportado. Envie um arquivo .srt, .vtt, .ass ou .ssa.",
    "fileReadError": "Erro ao ler o arquivo. Pode estar corrompido ou ser muito grande.",
    "charCountWarning": "Aviso: texto muito longo pode demorar mais ou atingir os limites da API.",
    "errorMissing": "A chave da API e o texto da legenda são obrigatórios.",
    "errorAPI": "Erro da API: {message}",
    "errorNetwork": "Erro de rede. Verifique sua conexão com a internet.",
    "errorUnknown": "Ocorreu um erro desconhecido. Tente novamente.",
    "errorNoDownloadText": "Nenhum texto traduzido disponível para download.",
    "apiKeyTooltip": "Digite a chave de API do provedor selecionado: do Google AI Studio para modelos Gemini, da plataforma DeepSeek para modelos DeepSeek, ou do console da Anthropic para modelos Claude. Esta chave é usada e armazenada apenas para esse provedor.",
    "saveApiKeyTooltip": "Se marcado, sua chave de API é armazenada localmente no seu navegador. Desmarque para removê-la.",
    "modelTooltip": "Os modelos de IA são atualizados e descontinuados com frequência. Modelos marcados com * costumam ser mais rápidos/baratos, mas têm limites de uso mais restritos. Sempre verifique os IDs exatos e os preços atuais na documentação oficial: ai.google.dev/gemini-api/docs/models para Gemini, api-docs.deepseek.com para DeepSeek, docs.claude.com para Claude.",
    "temperatureTooltip": "Valores mais baixos (ex: 0,2) geram traduções mais previsíveis e literais. Valores mais altos (ex: 0,9) incentivam mais criatividade e variedade de palavras. Padrão: 0,7",
    "toneTooltip": "Escolha o estilo e o tom do diálogo traduzido para combinar com o contexto do seu conteúdo.",
    "targetLangTooltip": "Escolha o idioma para o qual deseja traduzir as legendas.",
    "uploadFileTooltip": "Clique para enviar um arquivo de legenda (.srt, .vtt, .ass ou .ssa) do seu dispositivo.",
    "outputFileNameTooltip": "Digite um nome personalizado para o arquivo traduzido. Se deixado em branco, um nome será gerado automaticamente.",
    "customPromptLabel": "Instruções personalizadas (opcional):",
    "customPromptPlaceholder": "ex: Não traduza os nomes dos personagens / use um tom humorístico / use linguagem coloquial do dia a dia...",
    "customPromptTooltip": "Adicione instruções extras que deseja que o modelo siga ao traduzir. Isso é aplicado como orientação extra de estilo/contexto e não pode substituir as regras de formatação SRT/VTT.",
    "stopBtn": "Parar tradução",
    "translatingProgress": "Traduzindo bloco {current} de {total}...",
    "translationCancelled": "A tradução foi cancelada pelo usuário.",
    "manualModeLabel": "Modo de Tradução Manual (sem IA)",
    "manualModeTooltip": "Ative isso para traduzir linha por linha você mesmo, em vez de usar IA. O texto original aparece à esquerda; digite sua tradução à direita. Tudo é salvo automaticamente.",
    "manualEditorTitle": "Editor de Tradução Manual",
    "manualEditorEmptyHint": "Envie um arquivo de legenda ou cole o texto acima para começar.",
    "manualTranslationPlaceholder": "Digite sua tradução aqui...",
    "manualDownloadBtn": "Baixar arquivo SRT traduzido",
    "manualAutoSaveHint": "Tudo é salvo automaticamente neste navegador.",
    "chunkSizeLabel": "Volume de processamento por etapa:",
    "chunkSizeTooltip": "Quantas linhas de legenda são enviadas ao modelo por solicitação. Um valor menor é mais estável, mas exige mais solicitações; um valor maior é mais rápido e barato, mas aumenta um pouco o risco de dessincronização das linhas.",
    "chunkSizeOptimal": "Ideal (recomendado)",
    "chunkSizeHigh": "Alto",
    "chunkSizeVeryHigh": "Muito alto",
    "resumeBtn": "Retomar tradução",
    "partialTranslationSaved": "{current} de {total} partes traduzidas. Clique em \"Retomar tradução\" para continuar daqui.",
    "rateLimitLabel": "Atraso entre solicitações:",
    "rateLimitTooltip": "Adiciona uma pausa entre solicitações consecutivas ao modelo, reduzindo a chance de atingir o limite de taxa do provedor. Útil para arquivos grandes ou contas gratuitas.",
    "rateLimitOff": "Desligado",
    "rateLimitLow": "Baixo (1s)",
    "rateLimitMedium": "Médio (3s)",
    "rateLimitHigh": "Alto (6s)",
    "postProcessLabel": "Corrigir linhas longas automaticamente",
    "postProcessTooltip": "Após a tradução, divide automaticamente em duas as linhas que ficaram muito longas, para melhor legibilidade das legendas. Aplica-se apenas a SRT/VTT.",
    "assFormatNote": "Para arquivos ASS/SSA, apenas o texto do diálogo é traduzido - estilo, tempo e efeitos permanecem inalterados.",
},
"it": {
    "appTitle": "SubMovies - Traduttore di sottotitoli IA",
    "appHeaderTitle": "Traduttore intelligente SubMovies",
    "appSubtitle": "Traduci i tuoi sottotitoli senza sforzo e con precisione.",
    "apiKeyLabel": "Chiave API:",
    "apiKeyPlaceholder": "Inserisci qui la tua chiave API",
    "saveApiKeyLabel": "Salva chiave API",
    "modelLabel": "Modello IA:",
    "temperatureLabel": "Livello di creatività:",
    "toneLabel": "Tono di traduzione:",
    "langTargetLabel": "Lingua di destinazione:",
    "filenameLabel": "Nome del file di output:",
    "filenamePlaceholder": "es: MyTranslatedMovie.srt",
    "translateBtn": "Traduci sottotitoli",
    "fileChooseLabel": "Carica un file .srt, .vtt, .ass o .ssa:",
    "fileChooseButtonText": "Scegli file",
    "fileNone": "Nessun file scelto",
    "charCountLabel": "Caratteri: {count}",
    "promptPlaceholder": "Oppure incolla qui il testo dei sottotitoli (il formato SRT, VTT o ASS viene rilevato automaticamente)",
    "downloadBtn": "Scarica file tradotto",
    "copyBtnText": "Copia",
    "copySuccess": "Copiato negli appunti!",
    "copyFail": "Impossibile copiare il testo.",
    "translatingPlaceholder": "Traduzione in corso... attendere.",
    "responseTitle": "Confronto traduzione",
    "originalTitle": "Testo originale",
    "translatedTitle": "Testo tradotto",
    "themeToggleLight": "Passa alla modalità chiara",
    "themeToggleDark": "Passa alla modalità scura",
    "closeBtnLabel": "Chiudi",
    "footerMadeWith": "Realizzato con",
    "footerBy": "da",
    "footerAuthor": "GeekNeuron",
    "fileValidationSRTError": "File SRT non valido. Controlla il formato.",
    "fileValidationVTTError": "File VTT non valido. Intestazione WEBVTT mancante o formato errato.",
    "fileValidationASSError": "File ASS/SSA non valido. Impossibile trovare [Script Info], [Events] o righe Dialogue.",
    "unsupportedFileType": "Tipo di file non supportato. Carica un file .srt, .vtt, .ass o .ssa.",
    "fileReadError": "Errore durante la lettura del file. Potrebbe essere danneggiato o troppo grande.",
    "charCountWarning": "Attenzione: un testo molto lungo potrebbe richiedere più tempo o raggiungere i limiti dell'API.",
    "errorMissing": "Chiave API e testo dei sottotitoli sono obbligatori.",
    "errorAPI": "Errore API: {message}",
    "errorNetwork": "Errore di rete. Controlla la tua connessione internet.",
    "errorUnknown": "Si è verificato un errore sconosciuto. Riprova.",
    "errorNoDownloadText": "Nessun testo tradotto disponibile per il download.",
    "apiKeyTooltip": "Inserisci la chiave API del provider selezionato: da Google AI Studio per i modelli Gemini, dalla piattaforma DeepSeek per i modelli DeepSeek, oppure dalla console Anthropic per i modelli Claude. Questa chiave viene usata e salvata solo per quel provider.",
    "saveApiKeyTooltip": "Se selezionata, la tua chiave API viene salvata localmente nel browser. Deseleziona per rimuoverla.",
    "modelTooltip": "I modelli IA vengono aggiornati e ritirati frequentemente. I modelli contrassegnati con * sono generalmente più veloci/economici ma hanno limiti di utilizzo più severi. Controlla sempre gli ID esatti e i prezzi attuali nella documentazione ufficiale: ai.google.dev/gemini-api/docs/models per Gemini, api-docs.deepseek.com per DeepSeek, docs.claude.com per Claude.",
    "temperatureTooltip": "Valori più bassi (es. 0,2) offrono traduzioni più prevedibili e letterali. Valori più alti (es. 0,9) incoraggiano maggiore creatività e varietà lessicale. Predefinito: 0,7",
    "toneTooltip": "Scegli lo stile e il tono del dialogo tradotto in base al contesto dei tuoi contenuti.",
    "targetLangTooltip": "Scegli la lingua in cui vuoi tradurre i sottotitoli.",
    "uploadFileTooltip": "Fai clic per caricare un file di sottotitoli (.srt, .vtt, .ass o .ssa) dal tuo dispositivo.",
    "outputFileNameTooltip": "Inserisci un nome personalizzato per il file tradotto. Se lasciato vuoto, verrà generato automaticamente un nome.",
    "customPromptLabel": "Istruzioni personalizzate (opzionale):",
    "customPromptPlaceholder": "es: Non tradurre i nomi dei personaggi / usa un tono umoristico / usa un linguaggio colloquiale quotidiano...",
    "customPromptTooltip": "Aggiungi eventuali istruzioni extra che vuoi che il modello segua durante la traduzione. Viene applicato come guida extra di stile/contesto e non può sovrascrivere le regole di formattazione SRT/VTT.",
    "stopBtn": "Interrompi traduzione",
    "translatingProgress": "Traduzione del blocco {current} di {total}...",
    "translationCancelled": "La traduzione è stata annullata dall'utente.",
    "manualModeLabel": "Modalità di traduzione manuale (senza IA)",
    "manualModeTooltip": "Attiva questa modalità per tradurre riga per riga da solo invece di usare l'IA. Il testo originale appare a sinistra; digita la tua traduzione a destra. Tutto viene salvato automaticamente.",
    "manualEditorTitle": "Editor di traduzione manuale",
    "manualEditorEmptyHint": "Carica un file di sottotitoli o incolla il testo sopra per iniziare.",
    "manualTranslationPlaceholder": "Scrivi qui la tua traduzione...",
    "manualDownloadBtn": "Scarica il file SRT tradotto",
    "manualAutoSaveHint": "Tutto viene salvato automaticamente in questo browser.",
    "chunkSizeLabel": "Volume di elaborazione per fase:",
    "chunkSizeTooltip": "Quante righe di sottotitoli vengono inviate al modello per richiesta. Un valore più basso è più stabile ma richiede più richieste; un valore più alto è più veloce ed economico ma aumenta leggermente il rischio di disallineamento delle righe.",
    "chunkSizeOptimal": "Ottimale (consigliato)",
    "chunkSizeHigh": "Alto",
    "chunkSizeVeryHigh": "Molto alto",
    "resumeBtn": "Riprendi traduzione",
    "partialTranslationSaved": "{current} di {total} parti tradotte. Clicca su \"Riprendi traduzione\" per continuare da qui.",
    "rateLimitLabel": "Ritardo tra le richieste:",
    "rateLimitTooltip": "Aggiunge una pausa tra richieste consecutive al modello, riducendo il rischio di raggiungere il limite di frequenza del provider. Utile per file di grandi dimensioni o account gratuiti.",
    "rateLimitOff": "Disattivato",
    "rateLimitLow": "Basso (1s)",
    "rateLimitMedium": "Medio (3s)",
    "rateLimitHigh": "Alto (6s)",
    "postProcessLabel": "Correggi automaticamente le righe lunghe",
    "postProcessTooltip": "Dopo la traduzione, divide automaticamente in due le righe diventate troppo lunghe, per una migliore leggibilità dei sottotitoli. Si applica solo a SRT/VTT.",
    "assFormatNote": "Per i file ASS/SSA viene tradotto solo il testo di dialogo - stile, tempistica ed effetti restano invariati.",
},
}


def build_language(code, strings):
    data = dict(strings)  # copy
    data["models"] = {mid: f"{emoji} {name}" for mid, emoji, name in zip(MODEL_IDS, MODEL_EMOJI, MODEL_NAMES[code])}
    data["tones"] = TONES[code]
    return data


def main():
    for code, strings in STRINGS.items():
        data = build_language(code, strings)
        path = os.path.join(OUT_DIR, f"{code}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
            f.write("\n")
        print(f"wrote {path} ({len(data)} keys)")


if __name__ == "__main__":
    main()
